### ISSUE TITLE
Problem about compile erlami

### ISSUE THREAD

**Issue by jamescheng17** [marcelog/erlami#1]
Hi 

I'm getting error message while I compile erlami

The error message is below
ERROR: sh(git describe --always --tags)
failed with return code 128 and the following output:
fatal: Not a git repository (or any of the parent directories): .git

ERROR: compile failed while processing /Users/james/Documents/workspaces/erlang/erlami: rebar_abort
make: **\* [compile] Error 1

below is my step
1. download erlami source from github (erlami-master.zip)
2. execute rebar get-deps
3. execute make

it shows
jamestekiMacBook-Pro:erlami james$ make
./rebar clean
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
==> erlami (clean)
rm -rf rel/erlami
./rebar compile
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
==> goldrush (compile)
Compiled src/gr_param_sup.erl
Compiled src/gre.erl
Compiled src/gr_sup.erl
Compiled src/gr_manager_sup.erl
Compiled src/gr_counter_sup.erl
Compiled src/gr_manager.erl
Compiled src/gr_context.erl
Compiled src/gr_app.erl
Compiled src/gr_counter.erl
Compiled src/gr_param.erl
Compiled src/glc_ops.erl
Compiled src/glc_lib.erl
Compiled src/glc.erl
Compiled src/glc_code.erl
==> lager (compile)
Compiled src/lager_util.erl
Compiled src/lager_transform.erl
Compiled src/lager_sup.erl
Compiled src/lager_msg.erl
Compiled src/lager_handler_watcher_sup.erl
Compiled src/lager_handler_watcher.erl
Compiled src/lager_stdlib.erl
Compiled src/lager_trunc_io.erl
Compiled src/lager_default_formatter.erl
Compiled src/lager_format.erl
Compiled src/lager_crash_log.erl
Compiled src/lager_console_backend.erl
Compiled src/lager_config.erl
Compiled src/lager_common_test_backend.erl
Compiled src/lager_file_backend.erl
Compiled src/lager_backend_throttle.erl
Compiled src/lager_app.erl
Compiled src/lager.erl
Compiled src/error_logger_lager_h.erl
WARN:  Missing plugins: [rebar_covertool]
WARN:  Missing plugins: [rebar_covertool]
==> rebar (compile)
Compiled src/rmemo.erl
Compiled src/rebar_xref.erl
Compiled src/rebar_upgrade.erl
Compiled src/rebar_subdirs.erl
Compiled src/rebar_utils.erl
Compiled src/rebar_shell.erl
Compiled src/rebar_require_vsn.erl
Compiled src/rebar_templater.erl
Compiled src/rebar_rel_utils.erl
Compiled src/rebar_qc.erl
Compiled src/rebar_reltool.erl
Compiled src/rebar_protobuffs_compiler.erl
Compiled src/rebar_proto_gpb_compiler.erl
Compiled src/rebar_proto_compiler.erl
Compiled src/rebar_otp_appup.erl
Compiled src/rebar_otp_app.erl
Compiled src/rebar_neotoma_compiler.erl
Compiled src/rebar_metacmds.erl
Compiled src/rebar_log.erl
Compiled src/rebar_lfe_compiler.erl
Compiled src/rebar_mustache.erl
Compiled src/rebar_port_compiler.erl
Compiled src/rebar_file_utils.erl
Compiled src/rebar_escripter.erl
Compiled src/rebar_erlydtl_compiler.erl
Compiled src/rebar_eunit.erl
Compiled src/rebar_edoc.erl
Compiled src/rebar_getopt.erl
Compiled src/rebar_dia_compiler.erl
Compiled src/rebar_dialyzer.erl
Compiled src/rebar_ct.erl
Compiled src/rebar_erlc_compiler.erl
Compiled src/rebar_cover_utils.erl
Compiled src/rebar_config.erl
Compiled src/rebar_cleaner.erl
Compiled src/rebar_core.erl
Compiled src/rebar_asn1_compiler.erl
Compiled src/rebar_deps.erl
Compiled src/rebar_app_utils.erl
Compiled src/rebar_base_compiler.erl
Compiled src/rebar_appups.erl
Compiled src/rebar_abnfc_compiler.erl
Compiled src/rebar.erl
==> covertool (compile)
Compiled src/rebar_covertool.erl
Compiled src/covertool.erl
==> erlami (compile)
Compiled src/erlami_connection.erl
Compiled src/erlami_sup.erl
Compiled src/erlami_server_config.erl
Compiled src/erlami_tcp_connection.erl
src/erlami_ssl_connection.erl:87: Warning: variable 'Timeout' is unused
Compiled src/erlami_ssl_connection.erl
Compiled src/erlami_example.erl
Compiled src/erlami_reader.erl
Compiled src/erlami_message.erl
Compiled src/erlami_app.erl
Compiled src/erlami_client.erl
ERROR: sh(git describe --always --tags)
failed with return code 128 and the following output:
fatal: Not a git repository (or any of the parent directories): .git

ERROR: compile failed while processing /Users/james/Documents/workspaces/erlang/erlami: rebar_abort
make: **\* [compile] Error 1

---

I think I might have missed a few steps

thank you

**Comment by marcelog** [comment]
The issue seems to be that I'm using the git revision for the app version here: https://github.com/marcelog/erlami/blob/master/src/erlami.app.src#L20. When rebar compiles the app from the zip file there's no .git directory (thus, no revision information) and the compilation fails.

Please clone erlami using git or include it as a dependency in your own application (this is actually the intended way of using it since it's not that useful having it run as a standalone application).

Best!

**Comment by jamescheng17** [comment]
Hi 
Thank you for your reply
I Will try again
