### ISSUE TITLE
Still usable?

### ISSUE THREAD

**Issue by bweston92** [marcelog/erlami#2]
I want to dive into Erlang, this being my first project to connect to a asterisk server and `ORIGINATE` a call, any documentation on how that would be done using this as a library?

**Comment by marcelog** [comment]
Hello!

Check out the README, there's an example on how to create and send actions. You might also want to see the [erlami_message](https://github.com/marcelog/erlami/blob/master/src/erlami_message.erl) file.

Cheers!

**Comment by bweston92** [comment]
The readme I'm sorry to say doesn't show me how to install the library with Rebar. Maybe I should learn Erlang a bit more first :D sorry.
